### ISSUE TITLE
Cannot find module 'read-package-json-fast' when using v1.0.37

### ISSUE THREAD

**Issue by pioneer2k** [asyncapi/github-action-for-generator#127]
Describe the bug
When using the asyncapi/github-action-for-generator@v1.0.37 (and 1.0.36 as well) I get the following error in GitHub Actions:

Error: Cannot find module 'read-package-json-fast'
Require stack:
- /home/runner/work/_actions/asyncapi/github-action-for-generator/v1.0.37/node_modules/@npmcli/run-script/lib/run-script.js
- /home/runner/work/_actions/asyncapi/github-action-for-generator/v1.0.37/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/asyncapi/github-action-for-generator/v1.0.37/node_modules/@npmcli/run-script/lib/run-script.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)

How to Reproduce
use the github-action with v1.0.37 like this

 - name: Generating HTML from AsyncAPI document
    uses: asyncapi/github-action-for-generator@v1.0.37
    with:
      template: '@asyncapi/html-template@0.23.2' 
      filepath: src/main/resources/asyncapi.yml
      parameters: baseHref=/customer-context-asyncapi-generated-html/
      output: asyncapi/customer-context-asyncapi-generated-html
Expected behavior
no error

**Comment by derberg** [comment]
hmmm, the problem was there already right? with 1.0.35? and it was fixed 🤔

**Comment by pioneer2k** [comment]
no, I think we had problems with other packages before, but not with 'read-package-json-fast'

**Comment by derberg** [comment]
there was problem with several packages, including this one https://github.com/asyncapi/github-action-for-generator/issues/111#issuecomment-888420811 🤔

**Comment by pioneer2k** [comment]
Hi @derberg, what about a fix for this issue?

**Comment by derberg** [comment]
@pioneer2k can you check [this](https://github.com/asyncapi/github-action-for-generator/pull/148) out before we merge, like last time?

**Comment by pioneer2k** [comment]
@derberg  you mean this way?
asyncapi/github-action-for-generator@fbf42ecb7a3873b9d653a7f22377128c3a4d51fb

With that one I get the next error:
Error: Cannot find module 'json-parse-even-better-errors'

**Comment by derberg** [comment]
@pioneer2k can you try with `67b0dbaacd6f19f435b3f0fb1c6d5a48791aa0bc` please 🙏🏼

**Comment by pioneer2k** [comment]
@derberg 67b0dbaacd6f19f435b3f0fb1c6d5a48791aa0bc seems to work!

**Comment by pioneer2k** [comment]
@derberg will there be a new release with this fix? Currently this seems not to be the case.

**Comment by derberg** [comment]
@pioneer2k working on it since yesterday, windows broke my heart on CI level and then other stuff..... will let ya know here once release is out 🤞🏼

**Comment by pioneer2k** [comment]
@derberg today I tried the new release 1.0.47 - but it already fails in the very beginning of our pipeline (stage "Set up job"). Can you please have a look?

Download action repository 'asyncapi/github-action-for-generator@v1.0.47' (SHA:75e31e518d88f65692acb93d24f8c2ee613e04aa)
Error: Could not find file '/home/runner/work/_actions/_temp_d93ea6f1-264d-43c2-b756-c80601f6e04d/_staging/asyncapi-github-action-for-generator-75e31e5/node_modules/.bin/semantic-release'.

**Comment by derberg** [comment]
@pioneer2k omg, this GitHub action is killing me 😄 I guess I need to plan to start dockerizing it as GitHub Actions support now fetching image instead of code.

Could you try to remove [this](https://github.com/asyncapi/github-action-for-generator/blob/master/node_modules/.bin/semantic-release) file on your fork and test this action from your fork. I have no idea why this is happening, as `semantic-release` is not in `node_modules` as it is needed only for the release process, so maybe it is failing because of the entry in the `.bin` folder 🤷🏼

**Comment by pioneer2k** [comment]
@derberg do you think that could help to test with my own fork? I mean, testing with your last commit has worked, but not with the release.

**Comment by derberg** [comment]
@pioneer2k I remember I did some additional commits between your feedback and merge because of failing release pipeline

**Comment by pioneer2k** [comment]
@derberg with this commit from my fork it seems to work. No errors in my pipeline.

Download action repository 'pioneer2k/github-action-for-generator@019f61d7b0e558e305b9ec26e01e654ad5250784' (SHA:019f61d7b0e558e305b9ec26e01e654ad5250784)

**Comment by derberg** [comment]
@pioneer2k awesome, can you open a PR then?

**Comment by pioneer2k** [comment]
@derberg  there it is
https://github.com/asyncapi/github-action-for-generator/pull/158
